export const MENTOR_LIST_REQUEST = "MENTOR_LIST_REQUEST";
export const MENTOR_LIST_SUCCESS = "MENTOR_LIST_SUCCESS";
export const MENTOR_LIST_FAIL = "MENTOR_LIST_FAIL";

export const MENTOR_DETAILS_REQUEST = "MENTOR_DETAILS_REQUEST";
export const MENTOR_DETAILS_SUCCESS = "MENTOR_DETAILS_SUCCESS";
export const MENTOR_DETAILS_FAIL = "MENTOR_DETAILS_FAIL";

export const MENTOR_DELETE_REQUEST = "MENTOR_DELETE_REQUEST";
export const MENTOR_DELETE_SUCCESS = "MENTOR_DELETE_SUCCESS";
export const MENTOR_DELETE_FAIL = "MENTOR_DELETE_FAIL";

export const MENTOR_ADD_REQUEST = "MENTOR_ADD_REQUEST";
export const MENTOR_ADD_SUCCESS = "MENTOR_ADD_SUCCESS";
export const MENTOR_ADD_FAIL = "MENTOR_ADD_FAIL";
export const MENTOR_ADD_RESET = "MENTOR_ADD_RESET";

export const MENTOR_UPDATE_REQUEST = "MENTOR_UPDATE_REQUEST";
export const MENTOR_UPDATE_SUCCESS = "MENTOR_UPDATE_SUCCESS";
export const MENTOR_UPDATE_FAIL = "MENTOR_UPDATE_FAIL";
export const MENTOR_UPDATE_RESET = "MENTOR_UPDATE_RESET";

export const MENTOR_ADD_REVIEW_REQUEST = "MENTOR_ADD_REVIEW_REQUEST";
export const MENTOR_ADD_REVIEW_SUCCESS = "MENTOR_ADD_REVIEW_SUCCESS";
export const MENTOR_ADD_REVIEW_FAIL = "MENTOR_ADD_REVIEW_FAIL";
export const MENTOR_ADD_REVIEW_RESET = "MENTOR_AA_REVIEW_RESET";

export const MENTOR_TOP_REQUEST = "MENTOR_TOP_REQUEST";
export const MENTOR_TOP_SUCCESS = "MENTOR_TOP_SUCCESS";
export const MENTOR_TOP_FAIL = "MENTOR_TOP_FAIL";
